baseURL = "https://opencommsalliance.org/"
languageCode = "en-us"
title = "Open Comms Alliance"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
googleMapsAPIKey = "AIzaSyDX6FTiFE_a2_SI2FGG1GNGkv1zq55HvN8"
